name: build-full-image
on:
  workflow_dispatch:

jobs:
  base:
    runs-on: ubuntu-latest
    environment: build-packer-images
    timeout-minutes: 360 # 6 hours
    concurrency: build-full-image

    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v2

      - name: Check out Devolutions/actions
        uses: actions/checkout@v2
        with:
          repository: Devolutions/actions
          ref: master
          token: ${{ secrets.DEVOLUTIONSBOT_TOKEN }}
          path: ./.github/workflows

      - name: Run Terraform plan tests
        uses: ./.github/workflows/packer-build
        with:
          configFilePath: packer/dvls/full/
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          PKR_VAR_lab_git_ref: ${{ github.ref_name }}
